#!/usr/bin/env bash

set -eo pipefail

PUPPETBOARD_VERSION='git0dce4d8+epfl'

apt-get update &&
apt-get install -y git &&
rm -rf /var/lib/apt/lists/*
cd /app
rm -rf .git
rm -f .gitignore
git init .
git remote add origin https://github.com/camptocamp/puppetboard.git
git fetch --tags
git checkout ${PUPPETBOARD_VERSION}
cat << EOF > settings.py
import os

PUPPETDB_HOST =       os.getenv('PUPPETBOARD_PUPPETDB_HOST', 'puppetdb')
PUPPETDB_PORT =       int(os.getenv('PUPPETBOARD_PUPPETDB_PORT', '8080'))
PUPPETDB_SSL_VERIFY = os.getenv('PUPPETBOARD_PUPPETDB_SSL_VERIFY', 'False') == 'False'
if os.getenv('PUPPETBOARD_USE_SSL') == 'True':
  PUPPETDB_KEY =        os.getenv('PUPPETBOARD_PUPPETDB_KEY', '/app/puppetboard.key')
  PUPPETDB_CERT =       os.getenv('PUPPETBOARD_PUPPETDB_CERT', '/app/puppetboard.crt')
DEFAULT_ENVIRONMENT = os.getenv('PUPPETBOARD_DEFAULT_ENVIRONMENT', '*')
OVERVIEW_FILTER = os.getenv('PUPPETBOARD_OVERVIEW_FILTER', '')
EOF
