#!/usr/bin/env bash

set -eo pipefail

PUPPETBOARD_VERSION='v0.1.0'

apt-get update &&
apt-get install -y git &&
rm -rf /var/lib/apt/lists/*
cd /app
rm -rf .git
rm -f .gitignore
git init .
git remote add origin https://github.com/puppet-community/puppetboard.git
git remote update
git checkout ${PUPPETBOARD_VERSION}
cat << EOF > settings.py
import os

PUPPETDB_HOST = 'puppetdb'
PUPPETDB_PORT = 8081
PUPPETDB_SSL_VERIFY = False
PUPPETDB_KEY = '/app/puppetboard.key'
PUPPETDB_CERT = '/app/puppetboard.crt'
EOF
