#!/usr/bin/env bash

set -eo pipefail

apt-get update
apt-get install -y git
cd /app
rm -rf .git
rm -f .gitignore
git init .
git remote add origin https://github.com/puppet-community/puppetboard.git
git remote update
git checkout master
cat << EOF > settings.py
import os

PUPPETDB_HOST = os.environ.setdefault('PUPPETDB_HOST', 'puppetdb')
PUPPETDB_PORT = int(os.environ.setdefault('PUPPETDB_PORT', '8081'))
PUPPETDB_SSL_VERIFY = False
PUPPETDB_KEY = '/app/puppetboard.key'
PUPPETDB_CERT = '/app/puppetboard.crt'
EOF
